before:
  hooks:
    - go mod download
    - make generate
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/gurnel/main.go
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- github:
    owner: mikeraimondi
    name: homebrew-tap
  commit_author:
    name: goreleaserbot
    email: goreleaser@mikeraimondi.com
  homepage: "https://github.com/mikeraimondi/gurnel"
  description: "Daily journaling for hackers"
  skip_upload: auto
  dependencies:
    - git
  install: |
    bin.install "gurnel"
