name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    image: golangci/golangci-lint:v1.19

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: make check build
