name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    container : golangci/golangci-lint:v1.19

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        go get -u github.com/go-bindata/go-bindata/...
        make check build
